#! python3
A=[]
B=[]
C=[]
y=1
print ("A","B","C")
while y==1:
    x=input(" ")
    if x=="GOSTER":
        print("A arkadaşları",A)
        print("B arkadaşları",B)
        print("C arkadaşları",C)
    elif x=="EKLE A B" or x=="EKLE B A":
        a=A.count("B")
        if a==0:
            A.append("B")
            B.append("A")
            print("A ile B arkadaş oldu.")
        else:
            print("Zaten arkadaşlar!")
    elif x=="EKLE B C"or x=="EKLE C B":
        b = B.count("C")
        if b == 0:
            B.append("C")
            C.append("B")
            print("B ile C arkadaş oldu.")
        else:
            print("Zaten arkadaşlar!")
    elif x=="EKLE A C"or x=="EKLE C A":
        c = C.count("A")
        if  c== 0:
          A.append("C")
          C.append("A")
          print("A ile C arkadaş oldu.")
        else:
            print("Zaten arkadaşlar!")
    elif x=="SIL A B" or x=="SIL B A":
        a = A.count("B")
        if a == 1:
            A.remove("B")
            B.remove("A")
            print("A ile B artık arkadaş değil.")
        else:
            print("Zaten arkadaş değil")
    elif x == "SIL B C" or x == "SIL C B":
        b = B.count("C")
        if b == 1:
            B.remove("C")
            C.remove("B")
            print("B ile C artık arkadaş değil.")
        else:
            print("Zaten arkadaş değil")
    elif x == "SIL A C" or x == "SIL C A":
        c = C.count("A")
        if c == 1:
            A.remove("C")
            C.remove("A")
            print("A ile C artık arkadaş değil.")
        else:
            print("Zaten arkadaş değil")
    elif x=="KAPAT":
        break
        
#HOCANIN KODLARI
#! python3
A = []
B = []
C = []
print("Sosyal platform 3 kisiden olusuyor: A, B ve C\n")
while True:
    x = input()
    if x.split(" ")[0] == "EKLE":
        if (x.split(" ")[1] == "A" and x.split(" ")[2] == "B") or (x.split(" ")[1] == "B" and x.split(" ")[2] == "A"):
            if "A" not in B and "B" not in A:
                A.append("B")
                B.append("A")
                print("\n-- A ile B artik arkadas.\n")
            else:
                print("\n-- A ile B zaten arkadas!\n")

        elif (x.split(" ")[1] == "A" and x.split(" ")[2] == "C") or (x.split(" ")[1] == "C" and x.split(" ")[2] == "A"):
            if "A" not in C and "C" not in A:
                A.append("C")
                C.append("A")
                print("\n-- A ile C artik arkadas.\n")
            else:
                print("\n-- A ile C zaten arkadas!\n")

        elif (x.split(" ")[1] == "B" and x.split(" ")[2] == "C") or (x.split(" ")[1] == "C" and x.split(" ")[2] == "B"):
            if "B" not in C and "C" not in B:
                B.append("C")
                C.append("B")
                print("\n-- B ile C artik arkadas.\n")
            else:
                print("\n-- B ile C zaten arkadas!\n")


    if x.split(" ")[0] == "SIL":
        if (x.split(" ")[1] == "A" and x.split(" ")[2] == "B") or (x.split(" ")[1] == "B" and x.split(" ")[2] == "A"):
            if "A" in B and "B" in A:
                A.remove("B")
                B.remove("A")
                print("\n-- A ile B artik arkadas degil.\n")
            else:
                print("\n-- A ile B zaten arkadas degil!\n")

        elif (x.split(" ")[1] == "A" and x.split(" ")[2] == "C") or (x.split(" ")[1] == "C" and x.split(" ")[2] == "A"):
            if "A" in C and "C" in A:
                A.remove("C")
                C.remove("A")
                print("\n-- A ile C artik arkadas degil.\n")
            else:
                print("\n-- A ile C zaten arkadas degil!\n")

        elif (x.split(" ")[1] == "B" and x.split(" ")[2] == "C") or (x.split(" ")[1] == "C" and x.split(" ")[2] == "B"):
            if "B" in C and "C" in B:
                B.remove("C")
                C.remove("B")
                print("\n-- B ile C artik arkadas degil.\n")
            else:
                print("\n-- B ile C zaten arkadas degil!\n")

    elif x.split(" ")[0] == "KAPAT":
        break
    elif x == "GOSTER":
        print("\nA'nin arkadaslari: ", A)
        print("B'nin arkadaslari: ", B)
        print("C'nin arkadaslari: ", C ,"\n")
